### ISSUE TITLE
Multi-parameter capabilities

### ISSUE THREAD

**Issue by andreasbastian** [hanskellner/Fusion360ParaParam#2]
I'll probably work on this on my fork to get more familiar with the Fusion API, but I have a lot of applications in which I would like to be able to export huge numbers of files for a pretty detailed sampling of a parameter space consisting of two or more parametrs.  being able to iterate across two different parameters with different increments would be great and I have applications for everything up to five (or six) parameters.  Perhaps something to consider for any upcoming refactor is whether it would be possible to make it pretty straightforward to extend the script to traverse more than two parameters at once.  This will of course produce a huge number of files, but this number is not a problem for the application I have in mind.

**Comment by hanskellner** [comment]
Andreas -

Clarifying some details here.  Assume you have two parameters with start, end, and step values:
- Width (start = 1.0, end = 2.0, step = 0.25)
  >> Resulting values {1.0, 1.25, 1.5, 1.75, 2.0}
- Height (start = 2.0, end = 2.5, step = 0.1)
  >> Resulting values = {2.0, 2.1, 2.2, 2.3, 2.4, 2.5}

There are 5X6 = 30 variations using these settings.  Therefore the script would need to iterate over all of these combinations:

| Width | Height |
| --- | --- |
| 1.0 | 2.0 |
| 1.25 | 2.0 |
| 1.5 | 2.0 |
| 1.75 | 2.0 |
| 2.0 | 2.0 |
| 1.0 | 2.1 |
| 1.25 | 2.1 |
| 1.5 | 2.1 |
| 1.75 | 2.1 |
| 2.0 | 2.1 |

etc..

Is that what you would like the script to do?

**Comment by andreasbastian** [comment]
Yes, that's the functionality that I would like.  It's going to generate s
huge number of unique files, but that is ok.

Thanks!

**Comment by hanskellner** [comment]
Ok, the script now supports multiple parameters.  Please check out the updates.
