### ISSUE TITLE
Not showing in fusion.

### ISSUE THREAD

**Issue by baconjuggling** [hanskellner/Fusion360ParaParam#4]
After following the manual instructions for script installation,( as well S trying the github installer in the autodesk app store)
I cannot find ParaParam in the fusion GUI.
It doesn't show in the scripts and add ons menu, like other things I've installed
Is it still working? 
Does it work with a personal licence?

Help would be greatly appreciated. 
This seems like the most useful thing ever, once I can get it to work. 

E.

**Comment by hanskellner** [comment]
Hi @baconjuggling -

Sorry, support for Javascript was removed from Fusion 360 and this script hasn't yet been updated to Python.  I hope to get to it soon.

**Comment by hanskellner** [comment]
The script has been converted to Python and runs correctly within Fusion 360./
