### ISSUE TITLE
Issue with exporting in one project

### ISSUE THREAD

**Issue by Ne0nx3r0** [hanskellner/Fusion360ParaParam#6]
I was able to get this plugin working with previous projects but with this particular one I get the following error:
![error](https://github.com/hanskellner/Fusion360ParaParam/assets/568081/02ff33af-f2c2-4b44-ad19-8edd86e177bc)'

Is it because of the yellow warnings? those are fine, if possible I'd like to just export anyway and ignore the errors.

**Comment by Ne0nx3r0** [comment]
I'm not sure what happened but I closed F360 and re-opened and it works fine now. 
![images](https://github.com/hanskellner/Fusion360ParaParam/assets/568081/b057bcab-d691-4a0b-b9a4-5332a8a50265)

**Comment by hanskellner** [comment]
@Ne0nx3r0 Not sure why it failed in your case.  I'd blame some Fusion gremlins.  Glad you got it working.
